config/routes.rb
Rails.application.routes.draw do
  root 'login_pages#login'
  resources :tastes, only: %i[new create index]
  resources :users
  resources :followings, only: %i[create destroy]
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'  

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  # The user giving the follow
  belongs_to :follower, foreign_key: :follower_id, class_name: 'User'

  # The user being followed
  belongs_to :followed, foreign_key: :followed_id, class_name: 'User'

  validates :follower_id, :followed_id, presence: true
  validate :not_duplicate

  def not_duplicate
    duplicated = Following.where(follower_id: follower_id, followed_id: followed_id)
    errors.add(:followed_id, 'Can\'t follow a user that is already followed') unless duplicated.length.zero?
  end
end

app/models/taste.rb
class Taste < ApplicationRecord
  belongs_to :user, optional: true

  validates :text, presence: true, length: { maximum: 240 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_one_attached :coverimage

  # Will return an array of follows for the given user instance
  # has_many :received_follows, foreign_key: :followedid, class_name: 'Following'
  # Will return an array of users who follow the user instance
  has_many :followers, class_name: 'Following', foreign_key: 'follower_id', dependent: :destroy
  has_many :current_followers, through: :followers, source: 'followed', dependent: :destroy

  has_many :followeds, class_name: 'Following', foreign_key: 'followed_id', dependent: :destroy
  has_many :current_followeds, through: :followeds, source: 'follower', dependent: :destroy

  # Will return an array of opinions the given user instance has made
  has_many :tastes, dependent: :destroy

  scope :unfollowed, ->(list) { where.not(id: list) }
  scope :followed, ->(list) { where(id: list) }

  scope :not_current_user, ->(current) { where.not(id: current.id) }

  validates :username, uniqueness: true, presence: true, length: { maximum: 15 }
  validates :fullname, presence: true, length: { maximum: 40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    puts "this is the params #{params[:id]}"
    puts current_user.id

    following = current_user.followeds.new(followed_id: params[:id], follower_id: current_user.id)

    flash[:error] = 'Error' unless following.save
    redirect_to request.referrer
  end

  def destroy
    following = Following.find(params[:id])
    following.destroy
    redirect_to request.referrer
  end
end

app/controllers/login_pages_controller.rb
class LoginPagesController < ApplicationController
  before_action :logout

  def home; end

  private

  def logout
    # redirect_to tastes_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: params[:session][:username])
    if @user
      log_in @user
      redirect_to tastes_path
    else
      redirect_to root_path
    end
  end

  def destroy
    log_out @user if logged_in?
    redirect_to root_path
  end
end

app/controllers/tastes_controller.rb
class TastesController < ApplicationController
  before_action :require_login

  def index
    @taste = current_user.tastes.build if current_user
    @tastes = Taste.all.includes(:user)
    list = current_user.followeds.select(:follower_id)
    @who = User.all.unfollowed(list).includes([:photo_attachment]).not_current_user(current_user)
  end

  def new
    @taste = Taste.new
  end

  def create
    @taste = current_user.tastes.new(params_taste)
    if @taste.save
      redirect_to tastes_path
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  private

  def params_taste
    params.require(:taste).permit(:text)
  end

  def require_login
    return if logged_in?

    flash[:error] = 'You must be logged in to access'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :url_redirection, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      flash[:success] = 'Successfully signed up!'
      log_in @user
      redirect_to root_path
    else
      flash[:error] = 'Something went wrong!'
      render 'new'
    end
  end

  def show
    @taste = Taste.new
    @user = User.find(params[:id])
    @tastes = @user.tastes.all.order(created_at: :desc)
    list = @user.followers.select(:followed_id)
    @who = User.all.followed(list).includes([:photo_attachment])
  end

  def follow
    @user = User.find(params[:id])
    @user.current_followers << current_user
    redirect_to user_path(@user)
  end

  def unfollow
    @user = User.find(params[:id])
    @user.followers.find_by(followed_id: current_user.id).destroy
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
    @tastes = @user.tastes.all.order(created_at: :desc)
    list = @user.followers.select(:followed_id)
    @who = User.all.followed(list).includes([:photo_attachment])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params_user)
      flash[:success] = 'User was successfully updated'
      redirect_to @user
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  private

  def params_user
    params.require(:user).permit(:username, :fullname, :photo, :coverimage)
  end

  def url_redirection
    @user = User.find(params[:id])
    redirect_to(tastes_url) unless current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/login_pages_helper.rb
module LoginPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out(_user)
    session.delete :user_id
    @current_user = nil
  end
end

app/helpers/tastes_helper.rb
module TastesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def assign_images(user)
    if user.photo.attached?
      image_tag user.photo
    else
      user.photo.attach(io: File.open('app/assets/images/placeholder-photo.png'),
                        filename: 'placeholder-photo.png', content_type: 'image/png')
    end
  end

  def assign_coverimage(user)
    if user.coverimage.attached?
      image_tag user.coverimage
    else
      user.coverimage.attach(io: File.open('app/assets/images/placeholder-cover.png'),
                       filename: 'placeholder-cover.png', content_type: 'image/png')
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>The Booktastes' Site</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag asset_path('favicon.ico') %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% flash.each do |message_type, message| %>
  <div class="flash alert"><%= message %></div>
  <% end %>
  <%= yield %>
</body>

</html>

app/views/login_pages/login.html.erb
<div class="wrapper">
  <div class="left">
    <div class="left-inner">
      <div>
        <i class="fa fa-search"></i>
        Follow your favorite books.
      </div>
      <div>
        <i class="fa fa-heart"></i>
        Hear what people are reading about.
      </div>
      <div>
        <i class="fa fa-comment"></i>
        Join the conversation.
      </div>
    </div>  
  </div>
  <div class="right">
    <%= render 'sessions/new' %>
    
    <div class="right-center">
      <i class="fa fa-book"></i>
      <div>See what's happening in the book's world right now</div>
      <p>Join Booktastes today</p>

      <%= link_to 'Sign up', signup_path %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg">
    <%= link_to :tastes, class: 'main-logo navbar-brand px-4' do %>
    <i class='fa fa-book logo'> </i>
    <% end %>
    <div class='taster'>
      <ul class="navbar-nav mr-auto mt-lg-0 px-4">
        <li class='nav-item'><i class='fa fa-user logo'> </i><%= link_to ' Profile', user_path(current_user.id) %></li>
        <li class='ml-2'></li>
        <li class='nav-item'><i class='fa fa-user-times logo'> </i><%= link_to ' Log out', logout_path, method: :delete %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/tastes/_left_bar.html.erb
<aside class="left-bar">
  <div class="profile-header">
    <div class="user-photo float-left rounded-lg">
      <%= assign_images(current_user)%>
    </div>
    <div class="user-fullname"><br><%= current_user.fullname %>
      (<%= current_user.username %>)
    </div>
  </div><br><br>
  <div class="user-stats clearfix border border-dark pt-3 pl-4">
    <div>
      <p class="stat-num"><%= current_user.followeds.count %></p>
      <p>Following</p>
    </div>
    <div>
      <p class="stat-num"><%= current_user.followers.count %></p>
      <p><%= 'Follower'.pluralize(current_user.followers.count) %></p>
    </div>
  </div>
  <%= link_to tastes_path, class: yield(:home_button) do %>
    <i class="fa fa-home"></i>
    <div class="menu-item">Home</div>
  <% end %>

  <%= link_to user_path(current_user.id), class: yield(:profile_button) do %>
    <i class="fa fa-user"></i>
    <div class="menu-item">Profile</div>
  <% end %>

  <%= link_to edit_user_path(current_user.id), class: yield(:edit_button) do %>
    <i class="fa fa-pencil-square-o"></i>
    <div class="menu-item">Edit</div>
  <% end %>
</aside>

app/views/tastes/_new_taste.html.erb
<div class="taste-form-wrap">

  <div class="form-title">TASTE ABOUT SOME BOOK</div>
  <%= form_for @taste, url: tastes_path do |f| %>
  <%= f.text_field :text, class: 'form-input', placeholder: "Compose new taste" %>

  <% f.submit 'Taste it'%>
  <% end %>
</div>

app/views/tastes/_who_to_follow.html.erb
<aside class="profile">
  <p class="who-to-follow">Who to follow</p>
  <% if @user != current_user %>

      <% @who.each do |user| %>
        <%= link_to user_path(user.id), class: 'user-follow-link' do %>
        <div class="user-follow">
          <div class="user-follow-image">
            <%= assign_images(user) %>
          </div>
          <div class="user-follow-text">
            <div class="user-follow-fullname"><%= user.fullname %></div>
            <div class="user-follow-username"><%= user.username %></div>
          </div>
        </div>
        <% end %>
      <% end %>

  <% end %>

</aside>

app/views/tastes/create.html.erb
<h1>Tastes#create</h1>
<p>Find me in app/views/tastes/create.html.erb</p>

app/views/tastes/findout.html.erb
<h1>Tastes#findout</h1>
<p>Find me in app/views/tastes/findout.html.erb</p>

app/views/tastes/index.html.erb
<% provide(:home_button, ('active')) %>

<div class="main">
  <%= render 'left_bar' %>
  <div class="center-block">
    <%= render 'shared/header' %>
    <div class="center-wrap">
      <div class="taste-center">
        <div class="title-section">
          <div class="tastes-text">Tastes</div>
        </div>
        <%= render 'new_taste' %>

        <ul class="taste-list">
          <div class="tastes-count">
            <%= current_user.tastes.count %> NEW TASTES
          </div>
          <%  @tastes.each do |t| %>
          <li class="single-taste">

            <div class="taste-img-wrap">
              <div class="taste-image rounded-lg">
                <%= assign_images(t.user) %>
              </div>
            </div>

            <div class="taste-name-text">
              <div class="taste-fullname">
                <%= link_to t.user.fullname, user_path(t.user.id) %>
              </div>
              <div class="taste-date ml-4">
                <%= time_ago_in_words(t.created_at) %>
              </div>
              <p><%= t.text %></p>
            </div>

          </li>
          <% end %>
        </ul>
      </div>

      <%= render 'who_to_follow' %>
    </div>

  </div>

</div>

app/views/tastes/new.html.erb
<h1>Tastes#new</h1>
<p>Find me in app/views/tastes/new.html.erb</p>

app/views/users/_followed_by.html.erb
<div class="followed-by mt-4">
  <h2>Followed by</h2>
  <% unless @who.empty?%>
    <% @who.each do |user| %>
      <%= link_to user_path(user.id), class: 'user-follow-link' do %>
      <div class="user-follow">
        <div class="user-follow-image">
          <%= assign_images(user) %>
        </div>
        <div class="user-follow-text">
          <div class="user-follow-fullname"><%= user.fullname %></div>
          <div class="user-follow-username"><%= user.username %></div>
        </div>
      </div>
      <% end %>
    <% end %>
  <% else %>
  <div class="no-content py-2 mt-2">
  <p><%= @user.fullname %> has not follows yet.</p>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:edit_button, ('active' if @user == current_user)) %>
<div class="main">
  <%= render 'tastes/left_bar' %>
  <div class="center-block">
    <%= render 'shared/header' %>
    <div class="center-wrap">
      <div class="taste-center">
        <div class="profile-cover-image">
          <%= assign_coverimage(current_user)%>
        </div>
        <div class="title-section">
          <div class="tastes-text">Edit User</div>
        </div>
        <div class="edit-form signup-form-wrap mt-4 py-4">
          <%= form_for @user, url: "/users/#{params[:id]}" do |f| %>
            <%= f.label :'full name', class: 'form-label' %> <br>
            <%= f.text_field :fullname, class: 'form-input' %> <br>

            <%= f.label :'User name', class: 'form-label' %> <br>
            <%= f.text_field :username, class: 'form-input' %> <br>

            <%= f.label :photo, class: 'form-label' %> <br>
            <%= f.file_field :photo, accept: 'image/jpeg,image/gif,image/png' %> <br>

            <%= f.label :'cover image', class: 'form-label' %> <br>
            <%= f.file_field :coverimage, accept: 'image/jpeg,image/gif,image/png' %> <br><br>

            <%= f.submit 'Update', class: 'form-btn ' %>
          <% end %>
        </div>
      </div>

      <aside class="user-followings">
        <div class="profile-follow mr-4 pb-4 border-bottom">

          <% if current_user == @user %>

          <% elsif @current_user.current_followeds.include?(@user) %>
            <div class="follow-user mb-4">
              <%= link_to unfollow_user_path, title: 'Unfollow this user', method: 'POST' do %>
                  <i class="fa fa-close"></i>
              <% end %>
            </div>
          <% else %>
            <div class="follow-user mb-4">
              <%= link_to follow_user_path, title: 'Follow this user', method: 'POST' do %>
                <i class="fa fa-plus"></i>
              <% end %>
            </div>
          <% end %>

          <div class="profile-group mx-1">
            <div class="profile-img-link mt-4">
              <div class="user-image">
                <%= assign_images(@user)%>
              </div>
            </div>
            <div class="user-fullname"><%= @user.fullname %></div>
            <div class="user-username">@<%= @user.username %></div>
          </div>
          
          <div class="follow-user mb-4 disable"> <a href="#"><i class="fa fa-bars"></i></a>  </div>
        </div>

        <%= render 'followed_by' %>
      </aside>
    </div>
 
  </div>

</div>

app/views/users/new.html.erb
<div class="wrapper">
  <div class="left">
    <div class="left-inner">
      <div>
        <i class="fa fa-search"></i>
        Follow your favorite books.
      </div>
      <div>
        <i class="fa fa-heart"></i>
        Hear what people are reading about.
      </div>
      <div>
        <i class="fa fa-comment"></i>
        Join the conversation.
      </div>
    </div>
  </div>
  <div class="right">

    <div class="signup-form-wrap mt-4 py-4 right-center login-wrapper">

      <h2><i class="fa fa-book"></i> Sign Up</h2>
      <%= form_for @user, html: {multipart: true},url: signup_path do |f| %>
        <%= f.label :'full name', class: 'form-label' %> <br>
        <%= f.text_field :fullname, class: 'form-input' %>

        <%= f.label :'User name', class: 'form-label' %> <br>
        <%= f.text_field :username, class: 'form-input' %> 

        <%= f.label :photo, class: 'form-label' %> <br>
        <%= f.file_field :photo, accept: 'image/jpeg,image/gif,image/png' %> 

        <%= f.label :'cover image', class: 'form-label' %> <br>
        <%= f.file_field :coverimage, accept: 'image/jpeg,image/gif,image/png' %> <br><br>

        <%= f.submit 'Sign up', class: 'form-btn w-25' %>
        <%= link_to 'Log in', root_path, class: 'login-btn form-btn w-25' %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:profile_button, ('active' if @user == current_user)) %>
<div class="main">
  <%= render 'tastes/left_bar' %>
  <div class="center-block">
    <%= render 'shared/header' %>
    <div class="center-wrap">
      <div class="taste-center">
        <div class="profile-cover-image">
          <%= assign_coverimage(@user)%>
        </div>
        <div class="title-section">
          <div class="tastes-text">Profile</div>
        </div>
          <%= render 'tastes/new_taste' %>
        <ul class="taste-list">
          <div class="tastes-count">
            <%= @user.fullname.upcase %>'s TASTES
          </div>
          <% unless @tastes.empty?%>
            <%  @tastes.each do |t| %>
              <li class="single-taste">
                <div class="taste-img-wrap">
                  <div class="taste-image">
                    <%= assign_images(t.user) %>
                  </div>
                </div>
                <div class="taste-name-text">

                  <div class="taste-date ml-4">
                    <%= time_ago_in_words(t.created_at) %> ago
                  </div>
                  <p><%= t.text %></p>
                </div>
              </li>
            <% end %>
          <% else%>
          <div class="no-content p-3 mt-2">
            <p> <%= current_user.fullname %> has not tastes yet</p>
          </div>
          <% end %>
        </ul>
      </div>

      <aside class="user-followings">
        <div class="profile-follow mr-4">

            <% if current_user == @user %>

            <% elsif @current_user.current_followeds.include?(@user) %>
              <div class="follow-user mb-4">
                <%= link_to unfollow_user_path, title: 'Unfollow this user', method: 'POST' do %>
                    <i class="fa fa-close"></i>
                <% end %>
              </div>
            <% else %>
              <div class="follow-user mb-4">
                <%= link_to follow_user_path, title: 'Follow this user', method: 'POST' do %>
                  <i class="fa fa-plus"></i>
                <% end %>
              </div>
            <% end %>

          <div class="profile-group mx-1">
            <div class="profile-img-link mt-4">
              <div class="user-image">
                <%= assign_images(@user)%>
              </div>
            </div>
            <div class="user-fullname"><%= @user.fullname %></div>
            <div class="user-username">@<%= @user.username %></div>
          </div>
          
          <div class="follow-user mb-4 disable"> <a href="#"><i class="fa fa-bars"></i></a>  </div>
        </div>
        <div class="user-profile-stats">
          <div>
            <p class="stat-num"><%= @user.tastes.count %></p>
            <p class="stat-text"><%= 'Taste'.pluralize(@user.tastes.count) %></p>
          </div>
          <div class="stat-center">
            <p class="stat-num"><%= @user.followeds.count %></p>
            <p class="stat-text">Following</p>
          </div>
          <div>
            <p class="stat-num"><%= @user.followers.count %></p>
            <p class="stat-text"><%= 'Follower'.pluralize(@user.followers.count) %></p class="stat-text">
          </div>
        </div>
        <%= render 'followed_by' %>
      </aside>
    </div>
 
  </div>

</div>